name: Publish

on:
  push:
    branches: [ main ]
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  cargo_publish:
    runs-on: ubuntu-latest

    steps:  
    - name: publish
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
        toolchain: stable
        override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}